export var MenuNavbar = [
  {
    title: "New",
    patch: "/new",
    singleMenu: [
      { title: "WOMEN's", patch: "/new", styles: ["bold", "underline"] },
      { title: "Shoes", patch: "" },
      { title: "Bags", patch: "" },
      { title: "Accessories", patch: "" },
      { title: "MEN's", patch: "", styles: ["bold", "underline"] },
      { title: "Shoes", patch: "" },
    ],
  },
  {
    title: "Women",
    patch: "",
    megaMenu: [
      [
        { title: "SHOES", patch: "/new", styles: ["bold"] },
        { title: "Boots", patch: "" },
        { title: "Comfort", patch: "" },
        { title: "Flats", patch: "" },
        { title: "Loafers", patch: "" },
        { title: "Pumps", patch: "" },
        { title: "Sandals", patch: "" },
        { title: "Slip-ons", patch: "" },
        { title: "Sneakers", patch: "" },
        { title: "Water Shoes", patch: "" },
        { title: "Wedges", patch: "" },
      ],
      [
        { title: "Bags", patch: "", styles: ["bold"] },
        { title: "Clutches", patch: "" },
        { title: "Crossbodies", patch: "" },
        { title: "Shoulder Bags", patch: "" },
        { title: "Shoulder Bags", patch: "" },
        { title: "Tote Bags", patch: "" },
        { title: "Wallets", patch: "" },
      ],
      [
        { title: "Accessories", patch: "", styles: ["bold"] },
        { title: "Bracelets", patch: "" },
      ],
    ],
    img: {
      url: "https://cdn.shopify.com/s/files/1/0588/1443/1414/files/4_a62040eb-55f1-4fe2-be6a-bb21708776d7_700x700.jpg?v=1664828593",
      contentTitle: "",
      content: "",
    },
  },
  {
    title: "Men",
    patch: "",
    megaMenu: [
      [
        { title: "SHOES", styles: ["bold"], patch: "" },
        { title: "Boat Shoes", patch: "" },
        { title: "Loafers", patch: "" },
        { title: "Oxfords", patch: "" },
        { title: "Sandals", patch: "" },
        { title: "Slip-ons", patch: "" },
        { title: "Sneakers", patch: "" },
        { title: "Water Shoes", patch: "" },
      ],
      [
        { title: "BAGS", patch: "", styles: ["bold"] },
        { title: "Backpacks", patch: "" },
        { title: "Crossbodies", patch: "" },
      ],
      [
        { title: "ACCESSORIES", patch: "", styles: ["bold"] },
        { title: "Socks", patch: "" },
      ],
    ],
    img: {
      url: "https://cdn.shopify.com/s/files/1/0588/1443/1414/files/5_c5162f56-5d44-49be-8c1e-b2e792382fdc_700x700.jpg?v=1664828627",
      contentTitle: "",
      content: "",
    },
  },
  {
    title: "Sale",
    patch: "",
    singleMenu: [
      { title: "Women's", patch: "", styles: ["bold", "underline"] },
      { title: "Shoes", patch: "" },
      { title: "Bags", patch: "" },
      { title: "Accessories", patch: "" },
      { title: "Men's", patch: "", styles: ["bold", "underline"] },
      { title: "Shoes", patch: "" },
      { title: "Bags", patch: "" },
      { title: "Accessories", patch: "" },
    ],
  },
  {
    title: "GALERIA",
    patch: "",
    style: "large",
    megaMenu: [
      [
        { title: "WOMEN", patch: "", styles: ["bold"] },
        { title: "New In", patch: "" },
        { title: "Boots", patch: "" },
        { title: "Comfort", patch: "" },
        { title: "Flats", patch: "" },
        { title: "Loafers", patch: "" },
        { title: "Pumps", patch: "" },
        { title: "Sandals", patch: "" },
        { title: "Slip-ons", patch: "" },
        { title: "Sneakers", patch: "" },
        { title: "Wedges", patch: "" },
      ],
      [
        { title: "MEN", patch: "", styles: ["bold"] },
        { title: "New In", patch: "" },
        { title: "Boat Shoes", patch: "" },
        { title: "Boots", patch: "" },
        { title: "Comfort", patch: "" },
        { title: "Loafers", patch: "" },
        { title: "Oxfords", patch: "" },
        { title: "Sandals", patch: "" },
        { title: "Slip-ons", patch: "" },
        { title: "Sneakers", patch: "" },
        { title: "Water Shoes", patch: "" },
      ],
      [
        { title: "ACCESSORIES", patch: "", styles: ["bold"] },
        { title: "WOMEN'S", patch: "", styles: ["underline"] },
        { title: "Bags", patch: "" },
        { title: "Jewelry", patch: "" },
        { title: "MEN'S", patch: "", styles: ["underline"] },
        { title: "Bags", patch: "" },
        { title: <br />, patch: "" },
        { title: "SALE", patch: "", styles: ["bold"] },
        { title: "Women", patch: "" },
        { title: "Men", patch: "" },
      ],
    ],
    img: {
      url: "https://cdn.shopify.com/s/files/1/0588/1443/1414/files/0I9A9775-DropDownMenu_700x700.jpg?v=1669757197",
      contentTitle: "",
      content: "",
    },
  },
  {
    title: "Naturalizer",
    patch: "",
    singleMenu: [
      { title: "Shoes", patch: "", styles: ["bold", "underline"] },
      { title: "Boots", patch: "" },
      { title: "Comfort", patch: "" },
      { title: "Flats", patch: "" },
      { title: "Loafers", patch: "" },
      { title: "Pumps", patch: "" },
      { title: "Sandals", patch: "" },
      { title: "Slip-ons", patch: "" },
      { title: "Sneakers", patch: "" },
      { title: "Wedges", patch: "" },
    ],
  },
  {
    title: "Brands",
    patch: "",
    megaMenu: [
      [
        { title: "WOMEN'S", patch: "", styles: ["bold"] },
        { title: "Asics", patch: "" },
        { title: "BuDhaGirl", patch: "" },
        { title: "D.A.T.E.", patch: "" },
        { title: "Idoré", patch: "" },
        { title: "Jeffrey Campbell", patch: "" },
        { title: "Lacoste", patch: "" },
        { title: "New Balance", patch: "" },
        { title: "Reebok", patch: "" },
        { title: "United Nude", patch: "" },
        { title: "4CCCCEES", patch: "" },
        { title: "View all brands >", patch: "", styles: ["underline"] },
      ],
      [
        { title: "MEN'S", patch: "", styles: ["bold"] },
        { title: "Asics", patch: "" },
        { title: "D.A.T.E.", patch: "" },
        { title: "Lacoste", patch: "" },
        { title: "Marco Moretti", patch: "" },
        { title: "New Balance", patch: "" },
        { title: "Oceania", patch: "" },
        { title: "Reebok", patch: "" },
        { title: "Sperry Top Slider", patch: "" },
        { title: "TOMS", patch: "" },
        { title: "Voile Blanche", patch: "" },
        { title: "View all brands >", patch: "", styles: ["underline"] },
      ],
      [
        
      ]
    ],
    img: {
      url: "https://cdn.shopify.com/s/files/1/0588/1443/1414/files/6_50147cbb-de74-48d4-83b2-15ca34ef7c1a_700x700.jpg?v=1664828642",
      contentTitle: "",
      content: "",
    },
  },
  {
    title: "Holiday Styles Sale",
    patch: "",
    singleMenu: [
      { title: "Women's", patch: "", styles: ["bold", "underline"] },
      { title: "Shoes", patch: "" },
      { title: "Handbags", patch: "" },
    ],
  },
];
